### ISSUE TITLE
about concurrent trace

### ISSUE THREAD

**Issue by wiluen** [HPMLL/BurstGPT#2]
hi author, the same timestamp means concurrent request?
862919	ChatGPT	266	290	556	API log
862919	ChatGPT	166	212	378	API log
862919	ChatGPT	758	138	896	API log
862919	ChatGPT	482	226	708	API log
for example, there 4 requests simultaneous send to the server?
and What is the interval between timestamps？
Sincerely thank you.

**Comment by lzzmm** [comment]
Hi wiluen,

Thank you for your issue.

Since current timestamps are only accurate to seconds, these 4 requests are sent out within the same second, but in a sequential order.

We will make timestamps accurate to milliseconds in future collections.

Please feel free to ask if you have any other questions.

**Comment by wiluen** [comment]
Thank you for your reply. Looking forward to it very much
