### ISSUE TITLE
about regional GPT service providers

### ISSUE THREAD

**Issue by wiluen** [HPMLL/BurstGPT#3]
hi author,
in your paper, you say "We collected data from one of these regional GPT service providers with over 3,000 users"
Is this  regional GPT service providers only serving 3000 users, or are there more that you haven't counted？
Because I found that the requests are quite sparse.

**Comment by lzzmm** [comment]
Hi wiluen,

When we collected the traces in release v1.1, this GPT service was serving a region with 3000-4000 users. The requests are quite sparse because it is a real-world trace, not everybody uses GPT every day, and people may have used other GPT-like products. The API service exhibits a situation of calling a large number of times in a short period, which may be because users are collectively doing experiments, which is user behaviour in this trace. We provide two ways in our paper and also README.md for you to use our trace, you may scale the average Requests Per Second (RPS) to use our trace. Here is an example using BurstGPT for evaluation: [Llumnix](https://www.usenix.org/system/files/osdi24-sun-biao.pdf).
Please feel free to ask if you have any further questions, we're happy to help.

Best,
Yuhan
